/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <app_main.h>
#include <service.h>
#include <app_feature.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

volatile uint16_t adc_value = 0;
float converted_value = 0.0;

void service_init()
{
	rcc_init();
	adc_init_common(ADC_INDEPENDENT_MODE);
	adc1_init();
}

void app_init()
{
	;
}


int main(void)
{
	service_init();
	app_init();

	while (1)
	{
		get_adc_value(&adc_value);
		adc_convert_value(adc_value,&converted_value,TEMPERATURE_DETECTION_MODE);
	}
}
