/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <app_main.h>
#include <service.h>
#include <app_feature.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

void service_init()
{
	rcc_init();
	timer4_init();
	nvic_init(TIM4_ISR_NUMBER);
	pin_init(GREEN_LED_PIN,PIN_ALTERNATE_FUNCTION);
	pin_init(BLUE_LED_PIN,PIN_ALTERNATE_FUNCTION);
	pin_init(RED_LED_PIN,PIN_ALTERNATE_FUNCTION);
	pin_init(ORANGE_LED_PIN,PIN_ALTERNATE_FUNCTION);
}

void app_init()
{
	set_alternate_function_portD(GREEN_LED_PIN);
	set_alternate_function_portD(BLUE_LED_PIN);
	set_alternate_function_portD(RED_LED_PIN);
	set_alternate_function_portD(ORANGE_LED_PIN);
	timer4_set_generic(349,160);
	timer4_set_pwm(1);
	timer4_set_pwm(2);
	timer4_set_pwm(3);
	timer4_set_pwm(4);
	timer4_start();
}


int main(void)
{
	service_init();
	app_init();

	while (1)
	{
		;
	}
}
